### ISSUE TITLE
Replicating the results in the paper "Value targets in off-policy AlphaZero: a new greedy backup"

### ISSUE THREAD

**Issue by gemasphi** [danielwillemsen/alphazero-connect4#3]
Hey,

I would like to replicate the results in the paper "Value targets in off-policy AlphaZero: a new greedy backup". I was wondering if running the code in the branch off-policy would be enough? Or is there anything else extra that I should do?

Thanks.

**Comment by gemasphi** [comment]
I managed to do it, nevermind!

**Comment by danielwillemsen** [comment]
Hi @gemasphi ,

Thanks for you interest in this paper and repository. Probably, the code in the master branch would be the easiest to run. I'm happy to hear you already managed to get it working though. If you run into other issues, please let me know and I'll take a look!

Kind regards,

Daniel
